services:
  - type: web
    name: freelancer-web3
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: APTOS_NODE_URL
        value: https://api.testnet.aptoslabs.com
      - key: APTOS_NETWORK
        value: testnet
      - key: ZK_WASM_PATH
        value: public/zk/membership_js/membership.wasm
      - key: ZK_ZKEY_PATH
        value: public/zk/circuit.zkey
      - key: ZK_INPUT_PATH
        value: public/zk/input.json
      - key: ZK_VK_PATH
        value: public/zk/verification_key.json
